InvoiceApp/InvoiceApp/Models/Invoice.cs
using Microsoft.VisualBasic;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace InvoiceApp.Models
{
    public class Invoice
    {
        [Key]
        [Required]
        public int Id { get; set; }

        [Required]
        [StringLength(20)]
        [Display(Name = "Serial Number")]
        public string SerialNumber { get; set; }

        [Required]
        [StringLength(20)]
        [Display(Name = "Invoice Number")]
        public string InvoiceNumber { get; set; }

        [Required]
        [DataType (DataType.Date)]
        [Display(Name = "Invoice Date")]
        public DateTime InvoiceDate { get; set; }

        [Required]
        [DataType(DataType.Date)]
        [Display(Name = "Due Date")]
        public DateTime DueDate { get; set; }

        [Required]
        [ForeignKey("CustomerId")]
        [Display(Name = "Customer")]
        public Customer Customer { get; set; } 

        public List<InvoiceItem> Items { get; set; } = new List<InvoiceItem>();

        [NotMapped]
        public List<Customer> AvailableCustomers { get; set; } = new List<Customer>();

        [Required]
        [NotMapped]
        [Display(Name ="Customer Id")]
        public int SelectedCustomerId { get; set; }
    }

}

InvoiceApp/InvoiceApp/Controllers/InvoiceItemsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using InvoiceApp.Data;
using InvoiceApp.Models;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
namespace InvoiceApp.Controllers
{
    public class InvoiceItemsController : Controller
    {
        private readonly InvoiceAppDbContext _context;

        public InvoiceItemsController(InvoiceAppDbContext context)
        {
            _context = context;
        }

        // GET: InvoiceItem/Create
        public async Task<IActionResult> Create(int id)
        {
            var invoice = await _context.Invoice
                                            .Include(i => i.Customer)
                                            .Include(i => i.Items).ThenInclude(itm => itm.Product)
                                            .FirstOrDefaultAsync(i => i.Id == id);

            if (invoice is null)
            {
                return Redirect(Url.Action("Index", "Invoices"));
            }

            var model = new InvoiceItem();
            model.Invoice = invoice;
            model.AvailableProducts = await _context.Product.ToListAsync();

            return View(model);
        }

        // POST: InvoiceItem/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(int id, [FromForm][Bind("Quantity,Price,SelectedProductId")] InvoiceItem invoiceItem)
        {
            ModelState.Clear();

            var invoice = await _context.Invoice
                                            .Include(i => i.Customer)
                                            .Include(i => i.Items).ThenInclude(itm => itm.Product)
                                            .FirstOrDefaultAsync(i => i.Id == id);

            if (invoice is null)
            {
                return Redirect(Url.Action("Index", "Invoices"));
            }

            invoiceItem.Invoice = invoice;
            invoiceItem.AvailableProducts = await _context.Product.ToListAsync();

            var product = await _context.Product.FirstOrDefaultAsync(p => p.Id == invoiceItem.SelectedProductId);
            if (product is null)
            {
                ModelState.AddModelError("SelectedProductId", "Unable to find product");
                return View(invoice);
            }

            invoiceItem.Product = product;

            if (ModelState.IsValid)
            {
                _context.InvoiceItem.Add(invoiceItem);
                await _context.SaveChangesAsync();

                return Redirect(Url.Action("Details", "Invoices", new { invoiceItem.Invoice.Id }));
            }

            return View(invoiceItem);
        }

        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var invoiceItem = await _context.InvoiceItem
                .Include(itm => itm.Invoice)
                .Include(itm => itm.Product)
                .FirstOrDefaultAsync(m => m.Id == id);

            if (invoiceItem == null)
            {
                return NotFound();
            }

            return View(invoiceItem);
        }

        // POST: Invoices/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var invoiceItem = await _context.InvoiceItem
                .Include(itm => itm.Invoice)
                .FirstOrDefaultAsync(m => m.Id == id);

            _context.InvoiceItem.Remove(invoiceItem);
            await _context.SaveChangesAsync();

            return Redirect(Url.Action("Details", "Invoices", new { invoiceItem.Invoice.Id }));
        }
    }
}

InvoiceApp/InvoiceApp/Controllers/InvoicesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using InvoiceApp.Data;
using InvoiceApp.Models;
using Microsoft.EntityFrameworkCore.Metadata.Internal;

namespace InvoiceApp.Controllers
{
    public class InvoicesController : Controller
    {
        private const int DueDays = 30;
        private readonly InvoiceAppDbContext _context;

        public InvoicesController(InvoiceAppDbContext context)
        {
            _context = context;
        }

        // GET: Invoices
        public async Task<IActionResult> Index()
        {
           var invoiceList = await _context.Invoice.Include(i => i.Customer).ToListAsync();
           return View(invoiceList);
        }

        // GET: Invoices/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var invoice = await _context.Invoice
                .Include(i => i.Customer)
                .Include(i => i.Items).ThenInclude(itm => itm.Product)
                .FirstOrDefaultAsync(m => m.Id == id);

            if (invoice == null)
            {
                return NotFound();
            }

            return View(invoice);
        }

        // GET: Invoices/Create
        public async Task<IActionResult> Create()
        {
            var model = new Invoice();
            model.AvailableCustomers = await _context.Customer.ToListAsync();
            model.InvoiceDate = DateTime.Today;
            model.DueDate = model.InvoiceDate.AddDays(DueDays);
            return View(model);
        }

        // POST: Invoices/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("SerialNumber,InvoiceNumber,InvoiceDate,SelectedCustomerId")] Invoice invoice)
        {
            ModelState.Clear();
            var customer = await _context.Customer.FirstOrDefaultAsync(c => c.Id == invoice.SelectedCustomerId);
            if (customer is null)
            {
                ModelState.AddModelError("SelectedCustomerId", "Unable to find customer");
                return View(invoice);
            }

            invoice.Customer = customer;

            if (ModelState.IsValid)
            {
                invoice.DueDate = invoice.InvoiceDate.AddDays(DueDays);
                
                _context.Add(invoice);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(invoice);
        }

        // GET: Invoices/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var invoice = await _context.Invoice
                .Include(i => i.Customer)
                .FirstOrDefaultAsync(i => i.Id == id);

            if (invoice == null)
            {
                return NotFound();
            }

            invoice.AvailableCustomers = await _context.Customer.ToListAsync();
            invoice.SelectedCustomerId = invoice.Customer.Id;

            return View(invoice);
        }

        // POST: Invoices/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,SerialNumber,InvoiceNumber,InvoiceDate,SelectedCustomerId")] Invoice invoice)
        {
            if (id != invoice.Id)
            {
                return NotFound();
            }

            ModelState.Clear();
            var customer = await _context.Customer.FirstOrDefaultAsync(c => c.Id == invoice.SelectedCustomerId);
            if (customer is null)
            {
                ModelState.AddModelError("SelectedCustomerId", "Unable to find customer");
                return View(invoice);
            }

            invoice.Customer = customer;

            if (ModelState.IsValid)
            {
                try
                {
                    invoice.DueDate = invoice.InvoiceDate.AddDays(DueDays);

                    _context.Update(invoice);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!InvoiceExists(invoice.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(invoice);
        }

        // GET: Invoices/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var invoice = await _context.Invoice
                .FirstOrDefaultAsync(m => m.Id == id);
            if (invoice == null)
            {
                return NotFound();
            }

            return View(invoice);
        }

        // POST: Invoices/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var invoice = await _context.Invoice.FindAsync(id);
            _context.Invoice.Remove(invoice);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool InvoiceExists(int id)
        {
            return _context.Invoice.Any(e => e.Id == id);
        }
    }
}

InvoiceApp/InvoiceApp/Views/Invoices/Create.cshtml
@model InvoiceApp.Models.Invoice

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Create</h1>

<h4>Invoice</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="SerialNumber" class="control-label"></label>
                <input asp-for="SerialNumber" class="form-control" />
                <span asp-validation-for="SerialNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="InvoiceNumber" class="control-label"></label>
                <input asp-for="InvoiceNumber" class="form-control" />
                <span asp-validation-for="InvoiceNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="InvoiceDate" class="control-label"></label>
                <input asp-for="InvoiceDate" class="form-control" />
                <span asp-validation-for="InvoiceDate" class="text-danger"></span>
                <input type="hidden" asp-for="DueDate" />
            </div>
            
            <div class="form-group">
                <label asp-for="SelectedCustomerId" class="control-label"></label>              
                <select asp-for="SelectedCustomerId" asp-items="@(new SelectList(Model.AvailableCustomers,"Id","Name"))" class="form-control">
                </select>
                <span asp-validation-for="SelectedCustomerId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

InvoiceApp/InvoiceApp/Views/Invoices/Delete.cshtml
@model InvoiceApp.Models.Invoice

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Invoice</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.SerialNumber)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.SerialNumber)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.InvoiceNumber)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.InvoiceNumber)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.InvoiceDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.InvoiceDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DueDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DueDate)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

InvoiceApp/InvoiceApp/Views/Invoices/Details.cshtml
@model InvoiceApp.Models.Invoice

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Details</h1>

<div>
    <h4>Invoice</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Id)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Id)
        </dd>


        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.SerialNumber)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.SerialNumber)
        </dd>

        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.InvoiceNumber)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.InvoiceNumber)
        </dd>

        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.InvoiceDate)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.InvoiceDate)
        </dd>

        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.DueDate)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.DueDate)
        </dd>

        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Customer)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Customer.Name)
        </dd>
    </dl>
</div>

@await Html.PartialAsync("_InvoiceItemsList", Model)

<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

InvoiceApp/InvoiceApp/Views/Invoices/Edit.cshtml
@model InvoiceApp.Models.Invoice

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Edit</h1>

<h4>Invoice</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="SerialNumber" class="control-label"></label>
                <input asp-for="SerialNumber" class="form-control" />
                <span asp-validation-for="SerialNumber" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="InvoiceNumber" class="control-label"></label>
                <input asp-for="InvoiceNumber" class="form-control" />
                <span asp-validation-for="InvoiceNumber" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="InvoiceDate" class="control-label"></label>
                <input asp-for="InvoiceDate" class="form-control" />
                <span asp-validation-for="InvoiceDate" class="text-danger"></span>
                <input type="hidden" asp-for="DueDate" />
            </div>

            <div class="form-group">
                <label asp-for="SelectedCustomerId" class="control-label"></label>
                <select asp-for="SelectedCustomerId" asp-items="@(new SelectList(Model.AvailableCustomers,"Id","Name"))" class="form-control">
                </select>
                <span asp-validation-for="SelectedCustomerId" class="text-danger"></span>
            </div>

            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

InvoiceApp/InvoiceApp/Views/Invoices/Index.cshtml
@model IEnumerable<InvoiceApp.Models.Invoice>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.SerialNumber)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.InvoiceNumber)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.InvoiceDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DueDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Customer.Name)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.SerialNumber)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.InvoiceNumber)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.InvoiceDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DueDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Customer.Name)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
        }
    </tbody>
</table>
@*<html>
<body>
    <button type="button" class="btn btn-success">Add Product</button>
    <div class="form-group">
        <label for="name">Quantity:</label><br>
        <input type="number" id="txtQuantity" name="Quantity"><br><br/>
      
   
        <label for="name">Unit Price:</label><br>
        <input type="number" id="txtUnitPrice" name="UnitPrice"><br><br/>
   
        
        <label for="name">Total:</label><br>
        <input type="number" id="txtTotal" name="Total"><br><br/>
    <div/>

</body>
</html>*@

InvoiceApp/InvoiceApp/Views/Invoices/_InvoiceItemsList.cshtml
@model InvoiceApp.Models.Invoice

<div>
    <h5 class="float-left">Invoice Items</h5>
    <a asp-controller="InvoiceItems" asp-action="Create" asp-route-id="@Model.Id" class="float-right">Create New</a>
    <div class="clearfix"></div>
</div>



<table class="table">
    <thead>
        <tr>
            <th>Product</th>
            <th>Quantity</th>
            <th>Price</th>
            <th>Total</th>
            <th>&nbsp;</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.Items)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Product.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Quantity)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Price)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.LineTotalFormatted)
                </td>
                <td>
                    <a asp-controller="InvoiceItems" asp-action="Delete" asp-route-id="@item.Id" class="delete-btn" data-product="@item.Product.Name">Delete</a>
                </td>
            </tr>
        }
    </tbody>
    <tfoot>
        <tr>
            <td colspan="3">
                TOTAL
            </td>
            <td>
                @{
                    var invoiceTotal = Model.Items.Sum(invoiceItem => invoiceItem.LineTotal);
                    @Html.Raw($"{invoiceTotal:N2}");
                }
            </td>
            <td>&nbsp;</td>
        </tr>
    </tfoot>
</table>